### ISSUE TITLE
Add Github actions CI

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-utils#17]
## Story
As a contributor
I want my PR being automatically tested with CI process

## Background

TravisCI was disabled. 
Turn on GA with same flow as Travis was

## Acceptance criteria

GA runs tests on new PRs

**Comment by waymobetta** [comment]
It looks like tests are already being performed [here](https://github.com/ChainSafe/ChainBridge/blob/main/.github/workflows/ci.yml) whenever PRs are: opened, sync'd or reopened.

Close? Unless you were wanting this behavior on all branches?

**Comment by waymobetta** [comment]
^ Nevermind. This is being performed on ChainBridge not ChainBridge-Utils

**Comment by P1sar** [comment]
tests are falling, please  fix
